name: Client
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      working-directory: client/
      run: cargo build --verbose
    - name: Run tests
      working-directory: client/
      run: cargo test --verbose
    - name: Run
      working-directory: client/
      run: cargo run --verbose
