name: Server
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      working-directory: server/
      run: cargo build --verbose
    - name: Run tests
      working-directory: server/
      run: cargo test --verbose
    #- name: Run
     # working-directory: server/
      #run: cargo run --verbose
